name: Integration Tests

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: acme_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P3306 -uroot -proot --silent; do
          sleep 1
        done
        
    - name: Run Integration Tests
      run: mvn verify -Pintegration-test
      env:
        DATABASE_URL: jdbc:mysql://localhost:3306/acme_test
        DATABASE_USERNAME: root
        DATABASE_PASSWORD: root
        
    - name: Integration Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Integration Tests
        path: target/failsafe-reports/*.xml
        reporter: java-junit
