name: Unit Tests with Mocks/Stubs

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Run Unit Tests with Mocks
      run: |
        mvn clean test
        echo "Test report files:"
        find . -name "*.xml" -path "*/surefire-reports/*" | head -10
        
    - name: List generated files for debugging
      run: |
        echo "Current directory structure:"
        ls -la
        echo "Target directory contents:"
        ls -la target/ || echo "No target directory"
        echo "Surefire reports:"
        ls -la target/surefire-reports/ || echo "No surefire-reports directory"
        
    - name: Upload Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: JUnit Test Results
        path: target/surefire-reports/*.xml
        reporter: java-junit
